source 'https://rubygems.org'
ruby '3.1.4'
gem 'ruboty'
gem 'xrc'
gem 'ruboty-slack_rtm'
gem 'slack-api', github: 'standfirm/slack-ruby-gem', branch: 'workround-faye-websocket-security-issue'

# ruboty plugins
gem 'ruboty-alias'
gem 'ruboty-cloudfront', github: 'standfirm/ruboty-cloudfront', branch: 'fix-distribution-not-found'
gem 'ruboty-replace'
gem 'ruboty-balloon', github: 'shimomura1004/ruboty-balloon'
gem 'ruboty-callng'
gem 'ruboty-cron'
gem 'ruboty-echo'
gem 'ruboty-esa', github: 'kokuyouwind/ruboty-esa'
gem 'ruboty-github', github: 'standfirm/ruboty-github'
gem 'google-api-client'
gem 'google_drive'
gem 'googleauth'
gem 'ruboty-health_check', github: 'standfirm/ruboty-health_check'
gem 'ruboty-lgtm'
gem 'ruboty-misawa', github: 'mzp/ruboty-misawa'
gem 'ruboty-nullpo', github: 'mallowlabs/ruboty-nullpo'
gem 'ruboty-redash', github: 'mallowlabs/ruboty-redash'
gem 'ruboty-redis'
gem 'ruboty-shinchoku', github: 'mzp/ruboty-shinchoku'
gem 'ruboty-sorena', github: 'standfirm/ruboty-sorena'
gem 'ruboty-touban', github: 'hidakatsuya/ruboty-touban'
gem 'ruboty-wei', github: 'mzp/ruboty-wei'
gem 'ruboty-zoi', github: 'mallowlabs/ruboty-zoi'
gem 'ruboty-timeline', github: 'standfirm/ruboty-timeline', branch: 'use-uri_open'

gem "foreman"
