source 'https://rubygems.org'
ruby '2.4.3'
gem 'ruboty'
gem 'xrc'
gem 'ruboty-slack'
gem 'disable-ssl', github: 'mzp/disable-ssl'

# ruboty plugins
gem 'ruboty-alias'
gem 'ruboty-replace'
gem 'ruboty-aws', github: 'mzp/ruboty-aws'
gem 'ruboty-balloon', github: 'shimomura1004/ruboty-balloon'
gem 'ruboty-call'
gem 'ruboty-cron'
gem 'ruboty-echo'
gem 'ruboty-github', github: 'standfirm/ruboty-github'
gem 'ruboty-google_image'
gem 'google-api-client', '0.8.6'
gem 'google_drive', '1.0.1'
gem 'googleauth', '0.4.1'
gem 'ruboty-google_spreadsheet', github: 'mzp/ruboty-google_spreadsheet'
gem 'ruboty-growthforecast', github: 'mzp/ruboty-growthforecast'
gem 'ruboty-health_check', github: 'standfirm/ruboty-health_check'
gem 'ruboty-lgtm'
gem 'ruboty-misawa', github: 'mzp/ruboty-misawa'
gem 'ruboty-nullpo', github: 'mallowlabs/ruboty-nullpo'
gem 'ruboty-redis'
gem 'ruboty-shinchoku', github: 'mzp/ruboty-shinchoku'
gem 'ruboty-sorena', github: 'mallowlabs/ruboty-sorena'
gem 'ruboty-trello_quote', github: 'standfirm/ruboty-trello_quote'
gem 'ruboty-wei', github: 'mzp/ruboty-wei'
gem 'ruboty-yaminoma', github: 'Pegasus204/ruboty-yaminoma'
gem 'ruboty-zoi', github: 'mallowlabs/ruboty-zoi'
gem 'ruboty-timeline', github: 'mzp/ruboty-timeline'

gem "foreman"
