source 'https://rubygems.org'
ruby '2.7.2'
gem 'ruboty'
gem 'xrc'
gem 'ruboty-slack_rtm'

# ruboty plugins
gem 'ruboty-alias'
gem 'ruboty-cloudfront'
gem 'ruboty-replace'
gem 'ruboty-balloon', github: 'shimomura1004/ruboty-balloon'
gem 'ruboty-callng'
gem 'ruboty-cron'
gem 'ruboty-echo'
gem 'ruboty-esa', github: 'kokuyouwind/ruboty-esa'
gem 'ruboty-github', github: 'standfirm/ruboty-github'
gem 'ruboty-google_image'
gem 'google-api-client', '0.8.6'
gem 'google_drive'
gem 'googleauth'
gem 'ruboty-dictionary', github: 'hidakatsuya/ruboty-dictionary'
gem 'ruboty-growthforecast', github: 'mzp/ruboty-growthforecast'
gem 'ruboty-health_check', github: 'standfirm/ruboty-health_check'
gem 'ruboty-lgtm'
gem 'ruboty-misawa', github: 'mzp/ruboty-misawa'
gem 'ruboty-nullpo', github: 'mallowlabs/ruboty-nullpo'
gem 'ruboty-redash', github: 'mallowlabs/ruboty-redash'
gem 'ruboty-redis'
gem 'ruboty-shinchoku', github: 'mzp/ruboty-shinchoku'
gem 'ruboty-sorena', github: 'standfirm/ruboty-sorena'
gem 'ruboty-touban', github: 'hidakatsuya/ruboty-touban'
gem 'ruboty-wei', github: 'mzp/ruboty-wei'
gem 'ruboty-yaminoma', github: 'standfirm/ruboty-yaminoma'
gem 'ruboty-zoi', github: 'mallowlabs/ruboty-zoi'
gem 'ruboty-timeline', github: 'mzp/ruboty-timeline'
gem 'ruboty-trello_cleaner', github: 'mzp/ruboty-trello_cleaner'
gem 'ruboty-yasumimasu', github: 'standfirm/ruboty-yasumimasu'

gem "foreman"
